---
login:
  auth_username: "change_me"
  auth_password: "change_me"
  transport: "asyncssh"
  auth_strict_key: false

nodes:
  server:
    host: "192.168.7.1"
    platform: "esxi"
  rs814:
    host: "192.168.7.2"
    platform: "syno"
  c3750x:
    host: "192.168.7.3"
    platform: "ios"
...
